Update `setup`

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -52,7 +52,23 @@ function bincheck {
 bincheck kitty micro zoxide zsh
 
 if [ -f "/home/$SUDO_USER/.zshrc" ]; then
-    echo 'eval "$(zoxide init --cmd cd zsh)"' >>  "/home/$SUDO_USER/.zshrc"
+    read -p "Add zoxide init to .zshrc? [Y/n] " conf
+    case "$conf" in
+        y|Y|"" )
+             echo 'eval "$(zoxide init --cmd cd zsh)"' >>  "/home/$SUDO_USER/.zshrc" ;;
+        n|N ) :;;
+        * ) echo "Invalid Option"; exit 1;;
+    esac
+fi
+
+if [ $SHELL != $(which zsh) ]; then
+    echo -e "\e[1;33mW\e[0m: zsh is not set as your login shell"
+    read -p "Set $SUDO_USER's login shell to zsh? [Y/n] " conf
+    case "$conf" in
+        y|Y|"" ) usermod -s $(which zsh) $SUDO_USER;;
+        n|N ) :;;
+        * ) echo "Invalid Option"; exit 1;;
+    esac
 fi
 
 bincheck --install-cmd "curl -fsSL lure.sh/install | bash" lure
@@ -84,4 +100,3 @@ if [ ! -f /home/$SUDO_USER/.p10k.zsh ]; then
 else
 	echo -e "\e[1;34mI\e[0m: powerlevel10k theme is already installed"
 fi
-
