Synced @ Fri Nov 29 12:39:27 AM EST 2024

diff --git a/configs/micro/backups/%home%matcha%Documents%Git%myconfig%livesync b/configs/micro/backups/%home%matcha%Documents%Git%myconfig%livesync
--- a/configs/micro/backups/%home%matcha%Documents%Git%myconfig%livesync
+++ b/configs/micro/backups/%home%matcha%Documents%Git%myconfig%livesync
@@ -1,4 +1,22 @@
 #!/bin/bash
+
+dryrun=false
+
+while getopts ":hD" option; do
+	case $option in
+		h)  
+			echo "Usage: livesync [-h] [-D] <command>"
+            echo "Commands:"
+            echo "  push     Push configurations to the repo"
+            echo "  pull     Pull configurations from the repo"
+            exit 0 ;;
+		D) dryrun=true ;;
+		?) echo "error: option -$OPTARG does not exist"; exit 1 ;;
+	esac
+done
+
+shift $((OPTIND - 1))
+
 function copyconf {
 	name=$1
 	src=$2
@@ -12,25 +30,37 @@ function copyconf {
 	fi
 
 	# Looks like we're still here, copy the config
-	echo "Copying $name config to $dst..." | tee -a sync.log
+	echo "Copying $name config to $dst..." >> sync.log
 	# if the destination isn't found, make a directory
 	# (this is kinda hacky and evil but i cant think of a better way rn :/)
 	if [ ! -e $dst ]; then
-		mkdir -p $dst | tee -a sync.log
+		if $dryrun; then
+			echo "Dryrun: Creating directory $dst"
+		else
+			mkdir -p $dst | tee -a sync.log
+		fi
 	fi
 
 	# If the source is a directory, copy recursively and ignore git stuff
 	if [ -d $src ]; then
-		rsync -a -vv --exclude ".git*" $src $dst | tee -a sync.log
+		if $dryrun; then
+			echo "Dryrun: Copying directory $src to $dst"
+		else
+			rsync -a -vv --exclude ".git*" $src $dst | tee -a sync.log
+		fi
 	# else, just copy it
 	elif [ -f $src ]; then
-		rsync -vv $src $dst | tee -a sync.log
+		if $dryrun; then
+			echo "Dryrun: Copying file $src to $dst"
+		else
+			rsync -vv $src $dst | tee -a sync.log
+		fi
 	fi
 	echo -e "Done!\n" | tee -a sync.log
 	return 0
 }
 
-gitdir="$HOME/Documents/Git/myconfig"
+gitdir=$(readlink -f $0 | sed "s/\/livesync//")
 
 # Define config directories/paths
 kittyconf="$HOME/.config/kitty/kitty.conf"
@@ -40,12 +70,35 @@ p10kconf="$HOME/.p10k.zsh"
 microconf="$HOME/.config/micro"
 zoxidedb="$HOME/.local/share/zoxide/db.zo"
 
-# Copy them!
-copyconf "kitty" $kittyconf "$gitdir/configs/kitty/"
-copyconf "zsh" $zshconf "$gitdir/configs/zsh/"
-copyconf "oh-my-zsh" $omzconf "$gitdir/configs/oh-my-zsh"
-copyconf "p10k" $p10kconf "$gitdir/configs/p10k/"
-copyconf "micro" $microconf "$gitdir/configs/"
-copyconf "zoxide db" $zoxidedb "$gitdir/configs/zoxide/"
+case $1 in
+	"push") 
+		copyconf "kitty" $kittyconf "$gitdir/configs/kitty/"
+		copyconf "zsh" $zshconf "$gitdir/configs/zsh/"
+		copyconf "oh-my-zsh" $omzconf "$gitdir/configs/oh-my-zsh"
+		copyconf "p10k" $p10kconf "$gitdir/configs/p10k/"
+		copyconf "micro" $microconf "$gitdir/configs/"
+		copyconf "zoxide db" $zoxidedb "$gitdir/configs/zoxide/"
+		if [ ! $dryrun ]; then
+			git -C $gitdir add "$gitdir/*" && git -C $gitdir commit -a -m "Synced @ $(date)" && git -C $gitdir push
+		fi
+		exit 0 ;;
+		
+	"pull")
+		copyconf "kitty" "$gitdir/configs/kitty/" $kittyconf
+		copyconf "zsh" "$gitdir/configs/zsh/" $zshconf
+		copyconf "oh-my-zsh" "$gitdir/configs/oh-my-zsh" $omzconf
+		copyconf "p10k" "$gitdir/configs/p10k/" $p10kconf
+		copyconf "micro" "$gitdir/configs/" $microconf
+		copyconf "zoxide db" "$gitdir/configs/zoxide/" $zoxidedb
+		exit 0 ;;
 
-git -C $gitdir add "$gitdir/configs/*" && git -C $gitdir commit -a -m "Synced @ $(date)" && git -C $gitdir push
+	"")
+		echo "Usage: livesync [-h] [-D] <command>"
+        echo "Commands:"
+        echo "  push     Push configurations to the repo"
+        echo "  pull     Pull configurations from the repo"
+        exit 0 ;;
+	*)
+		echo "Unknown command: $1"
+		exit 1 ;;
+esac
